### ISSUE TITLE
getting stuck

### ISSUE THREAD

**Issue by mgazzin** [m-bers/Arch-Linux-Arm-M1#2]
Hi @m-bers , interesting project.

I am trying to adjust build.sh in the way it can work in Manjaro Linux.
I have made some small adjustments in build.sh:

https://github.com/mgazzin/Arch-Linux-Arm-M1/blob/main/build.sh

but command:

_sudo ./boot.exp_

fails with the following error:

![image](https://user-images.githubusercontent.com/7835130/144749776-55f36fb1-50c4-418a-9cf9-0f4f94b9790a.png)

can you give any hint on how to solve it?

**Comment by m-bers** [comment]
So two comments here. One is that you actually need to wait until PXE4/PXE6/HTTP4/HTTP6 boot attempts finish, then it will load startup.nsh to boot from the disk image.
Second comment is that manjaro is out of scope for this project and I don't think they have a generic ARM image that works.
